class ResponseCode:
    OK = 200
    INTERNAL_SERVER_ERROR = 500
    NOT_FOUND = 404
    FORBIDDEN = 403


class ResponseMessages:
    OK = 'OK'
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
    NOT_FOUND = 'NOT_FOUND'
    FORBIDDEN = 'FORBIDDEN'
